SELECT I.REST_ID ,I.REST_NAME , I.FOOD_TYPE , I.FAVORITES , I.ADDRESS , ROUND(R.SCORE ,2) SCORE
FROM REST_INFO I JOIN (SELECT REST_ID , AVG(REVIEW_SCORE) SCORE 
                       FROM REST_REVIEW
                       GROUP BY REST_ID) R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC , FAVORITES DESC