SELECT D.DEPT_ID , D.DEPT_NAME_EN , ROUND(E.AVG_SAL) AVG_SAL
FROM HR_DEPARTMENT D JOIN (SELECT DEPT_ID , AVG(SAL) AVG_SAL 
                           FROM HR_EMPLOYEES
                           GROUP BY(DEPT_ID)) E ON D.DEPT_ID = E.DEPT_ID
ORDER BY AVG_SAL DESC                        